// <auto-generated />
using Carefully.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carefully.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20221013213720_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Carefully.EnumsAreFun.EnumPayload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbstractionTypes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetsTypes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Payloads");
                });
#pragma warning restore 612, 618
        }
    }
}
